<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="MetaBrainz.MusicBrainz"/>
        <PackageReference Include="MetaBrainz.MusicBrainz.CoverArt"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MusicCatalog.Contracts\MusicCatalog.Contracts.csproj"/>
    </ItemGroup>
</Project>
