/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                    releasedAfter?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AlbumListItemDtoPagedResult"];
                        "application/json": components["schemas"]["AlbumListItemDtoPagedResult"];
                        "text/json": components["schemas"]["AlbumListItemDtoPagedResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/albums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AlbumDto"];
                        "application/json": components["schemas"]["AlbumDto"];
                        "text/json": components["schemas"]["AlbumDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateAlbumRequest"];
                    "text/json": components["schemas"]["UpdateAlbumRequest"];
                    "application/*+json": components["schemas"]["UpdateAlbumRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AlbumDto"];
                        "application/json": components["schemas"]["AlbumDto"];
                        "text/json": components["schemas"]["AlbumDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": boolean;
                        "application/json": boolean;
                        "text/json": boolean;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/albums/{albumId}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    albumId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TrackDto"][];
                        "application/json": components["schemas"]["TrackDto"][];
                        "text/json": components["schemas"]["TrackDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    albumId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateTrackRequest"];
                    "text/json": components["schemas"]["CreateTrackRequest"];
                    "application/*+json": components["schemas"]["CreateTrackRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TrackDto"];
                        "application/json": components["schemas"]["TrackDto"];
                        "text/json": components["schemas"]["TrackDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ArtistDtoPagedResult"];
                        "application/json": components["schemas"]["ArtistDtoPagedResult"];
                        "text/json": components["schemas"]["ArtistDtoPagedResult"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateArtistRequest"];
                    "text/json": components["schemas"]["CreateArtistRequest"];
                    "application/*+json": components["schemas"]["CreateArtistRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ArtistDto"];
                        "application/json": components["schemas"]["ArtistDto"];
                        "text/json": components["schemas"]["ArtistDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ArtistDto"];
                        "application/json": components["schemas"]["ArtistDto"];
                        "text/json": components["schemas"]["ArtistDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateArtistRequest"];
                    "text/json": components["schemas"]["UpdateArtistRequest"];
                    "application/*+json": components["schemas"]["UpdateArtistRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ArtistDto"];
                        "application/json": components["schemas"]["ArtistDto"];
                        "text/json": components["schemas"]["ArtistDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": boolean;
                        "application/json": boolean;
                        "text/json": boolean;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists/{artistId}/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path: {
                    artistId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AlbumListItemDtoPagedResult"];
                        "application/json": components["schemas"]["AlbumListItemDtoPagedResult"];
                        "text/json": components["schemas"]["AlbumListItemDtoPagedResult"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    artistId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateAlbumRequest"];
                    "text/json": components["schemas"]["CreateAlbumRequest"];
                    "application/*+json": components["schemas"]["CreateAlbumRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AlbumDto"];
                        "application/json": components["schemas"]["AlbumDto"];
                        "text/json": components["schemas"]["AlbumDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/genres/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GenreDto"];
                        "application/json": components["schemas"]["GenreDto"];
                        "text/json": components["schemas"]["GenreDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateGenreRequest"];
                    "text/json": components["schemas"]["CreateGenreRequest"];
                    "application/*+json": components["schemas"]["CreateGenreRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GenreDto"];
                        "application/json": components["schemas"]["GenreDto"];
                        "text/json": components["schemas"]["GenreDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlbumDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            artistId?: string;
            title?: string | null;
            /** Format: int32 */
            releaseYear?: number | null;
        };
        AlbumListItemDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            artistId?: string;
            artistName?: string | null;
            title?: string | null;
            /** Format: int32 */
            releaseYear?: number | null;
        };
        AlbumListItemDtoPagedResult: {
            items?: components["schemas"]["AlbumListItemDto"][] | null;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            readonly totalPages?: number;
        };
        ArtistDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            country?: string | null;
        };
        ArtistDtoPagedResult: {
            items?: components["schemas"]["ArtistDto"][] | null;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            readonly totalPages?: number;
        };
        CreateAlbumRequest: {
            title?: string | null;
            /** Format: int32 */
            releaseYear?: number | null;
        };
        CreateArtistRequest: {
            name?: string | null;
            country?: string | null;
        };
        CreateGenreRequest: {
            title?: string | null;
        };
        CreateTrackRequest: {
            /** Format: int32 */
            trackNumber?: number;
            title?: string | null;
            /** Format: int32 */
            durationSeconds?: number | null;
        };
        GenreDto: {
            /** Format: uuid */
            id?: string;
            title?: string | null;
        };
        LoginRequest: {
            email?: string | null;
            password?: string | null;
        };
        LoginResponse: {
            accessToken?: string | null;
            /** Format: date-time */
            expiresAtUtc?: string;
        };
        RegisterRequest: {
            email?: string | null;
            password?: string | null;
            displayName?: string | null;
        };
        TrackDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            albumId?: string;
            /** Format: int32 */
            trackNumber?: number;
            title?: string | null;
            /** Format: int32 */
            durationSeconds?: number | null;
        };
        UpdateAlbumRequest: {
            title?: string | null;
            /** Format: int32 */
            releaseYear?: number | null;
        };
        UpdateArtistRequest: {
            name?: string | null;
            country?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
